config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  devise_for :users, :controllers => {:registrations => "user/registration"}
  get 'home/about'
  resources :users,only: [:show,:index,:edit,:update] do
     member do
       get :following, :followers
     end
   end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments,only: [:create,:destroy]
  end
  resources :relationships, only: [:create,:destroy]
  resources :rooms
  
   get '/search' ,to: 'searchs#search'
   
   
  
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable
         
  has_many :favorite_book, through: :favorites, source: :book
  has_many :books, dependent: :destroy
  has_many :book_comments,dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following,through: :active_relationships,source: :followed
  has_many :followers,through: :passive_relationships,source: :follower
  has_many :chats
  has_many :user_rooms
  has_many :rooms,through: :user_rooms
  attachment :profile_image, destroy: false
  validates :name, presence:true
  
  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
  
# def self.search(search)
#       if search
#         where(['name LIKE ?', "%#{search}%"])
#       else
        
#       end
# end
 
def User.search(search, user_or_book, how_search)
    if user_or_book == "1"
      if how_search == "1"
           User.where(['name LIKE ?', "%#{search}%"])
      elsif how_search == "2"
            User.where(['name LIKE ?', "%#{search}"])
      elsif how_search == "3"
            User.where(['name LIKE ?', "#{search}%"])
      elsif how_search == "4"
            User.where(['name LIKE ?', "#{search}"])
      else
            User.all
      end
    end
end

 include JpPrefecture
  jp_prefecture :prefecture_code
  
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
 
  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}
end

app/controllers/user/registration_controller.rb
class User::RegistrationController < Devise::RegistrationsController

def create
 super 
  if @user.save
  ThanksMailer.send_confirm_to_user(@user).deliver_now
end
end

end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!
	before_action :baria_user, only: [:edit,:following,:followers]
	# before_action :

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  	@currentUserUserRoom = UserRoom.where(user_id: current_user.id)
  	@userUserRoom = UserRoom.where(user_id: @user.id)
  	unless @user.id == current_user.id
  	@currentUserUserRoom.each do |f|
  	 @userUserRoom.each do |u|
  	  if f.room_id == u.room_id then
  	   @isRoom = true
  	   @roomId = f.room_id
  	  end
  	 end
  end
  unless @isRoom
    @room = Room.new
    @user_room = UserRoom.new
  end
  end
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  	
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end



def following
 @title = "フォロー"
 @user = User.find(params[:id])
 @users = @user.following
 render 'following_show'
end

def followers
 @title = "Followers"
 @user = User.find(params[:id])
 @users = @user.followers
 render 'followers_show'
end

include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end


  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image,
  	:postcode, :prefecture_name, :address_city, :address_street)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end


end

app/helpers/user/registration_helper.rb
module User::RegistrationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build,remote:true) do |f| %>
<%= hidden_field_tag :followed_id, user.id %>
<%= f.submit "フォロー",class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless user == current_user %>
  <div id="follow_form">
  <% if current_user.following?(user) %>
    <%= render 'users/unfollow', user:user %>
  <% else %>
    <%= render 'users/follow' ,user:user%>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<h2>Your address</h2>
<div class="field">
  <%= f.label :postcode %> <br>
  <%= f.text_field :postcode ,autofocus: true, placeholder: 'postcode', class: "postcode" %>
  </div>
  <div class="field">
  <p>prefecture</p>
  <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name, class: "都道府県" %>
  </div>
  <div class="field">
  <p>city</p>
  <%= f.text_field :address_city %>
  </div>
  <div class="field">
  <p>street</p>
  <%= f.text_field :address_street %>
</div>

app/views/users/_profile.html.erb
<table class="table">
		<td><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></td>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
      <th><%= current_user.favorites.count %>いいね</th>
      <th>コメント数: <%= current_user.book_comments.count %></th>
    </tr>
		<tr>
			<div class="stats"><%= render 'shared/stats', user:user %></div>
		</tr>
</table>
<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
            html: { method: :delete },
            remote:true) do |f| %>
<%= f.submit "アンフォロー",class: "btn btn-danger" %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
<div class="row">
<div class="col-xs-6">
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %><br>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %><br>
</div>

<div class="field">
	<%= f.label :introduction %><br>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit "Update User",class: "btn btn-primary" %>
</div>

<% end %>
</div>
</div>
</div>

app/views/users/followers_show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 offset-xs-2">
<h1>Followers</h1>
<table class="table">
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<div class="stats"><%= render 'shared/stats', user:user %></div>
			
			<td><%= render 'follow_form',user:user %></td>
			
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>
</div>

app/views/users/following_show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 offset-xs-2">
<h1>Following</h1>
		<table class="table">
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<div class="stats"><%= render 'shared/stats', user:user %></div>
			
			<td><%= render 'follow_form',user:user %></td>
			
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>
</div>

app/views/users/index.html.erb
<div class="container">
<div class="row">
<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: current_user %>
<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>
</div>

<div class="col-xs-9">
	<% if user_signed_in? %>
	<%= render 'searchs/search' %>
	<% end %>
<h2>Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<div class="stats"><%= render 'shared/stats', user:user %></div>
			
			<td><%= render 'follow_form',user:user %></td>
			
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>
</div>
<!--users一覧 -->

app/views/users/show.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-3">
<h2>User info</h2>
		<%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %>
<table class="table">
		<tr>
			<th>name</th>
			<th><%= @user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= @user.introduction %></th>
		</tr>
		<tr>
      <th><%= current_user.favorites.count %>いいね</th>
      <th>コメント数: <%= current_user.book_comments.count %></th>
    </tr>
    	<tr>
			<div class="stats"><%= render 'shared/stats', user:@user %></div>
		</tr>
</table>

<% if @user.id == current_user.id %>
<div class="row">
	<%= link_to '',edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %>
</div>
<% end %>
<% if @user.id !=current_user %>
	<%= render 'follow_form',user:@user ,class: "col-xs-12"%>
	<% end %>
	<!--チャット機能-->
	<% unless @user.id == current_user.id %>
  <% if @isRoom == true %>
    <%= link_to "チャットへGo!", room_path(@roomId) ,class: "btn btn-success"%>
  <% else %>
    <%= form_for @room do |f| %>
      <%= fields_for @user_room do |e| %>
        <%= e.hidden_field :user_id, :value=> @user.id %>
      <% end %>
      <%= f.submit "チャットを始める" ,class: "btn btn-success"%>
    <% end %>
  <% end %>
<% end %>
	
	
	
	
<h2>New book</h2>
<%= render 'books/newform', book: @book %>
</div>
	<div class="col-xs-9">
<h2>Books</h2>
<!--books一覧 -->
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td>
				<%= link_to (book.user) do %>
				<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
				<% end %>
			</td>
			<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
			<td><%= book.body %></td>
			<td><p class="comment-count">コメント数: <%= book.book_comments.count %></p></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>
</div>
<!--books一覧 -->

<!--map-->
<% if @user.id == current_user.id %>
<h1>〒<%= @user.postcode %></h1>
<h1><%= @user.prefecture_code %></h1>
<h1 id="address"><%="#{@user.prefecture_code}#{@user.address_city}#{@user.address_street}" %></h1>
<% end %>
<h2>gmap</h2>
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
let map
window.onload = function(){
initMap();
codeAddress();
}

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 43.2203, lng:142.8634},
    zoom: 7,
  });

  marker = new google.maps.Marker({
    position:  {lat: 43.2203, lng:142.8634},
    map: map
  });
}
function codeAddress(){
  // 入力を取得
  var inputaddress = document.getElementById("address").textContent

  // geocodingしたあとmapを移動
  geocoder.geocode( { 'address': inputaddress }, function(results, status) {
    if (status == 'OK') {
　　　　　　　　　　　　// map.setCenterで地図が移動
      map.setCenter(results[0].geometry.location);

　　　　　　　　　　　　// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });
}
</script>
<script src=<%= ENV['KEY'] %> async defer></script>

app/views/users/show_follow.html.erb
<!--フォローしているユーザーとフォロワーの両方を表示する-->
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Books:</b> <%= @user.book_comment.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            	<%= attachment_image_tag(user, :profile_image, :fill, 30, 30, fallback: "no-image-mini.jpg") %><br>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
    <% end %>
  </div>
</div>